### ISSUE TITLE
Move GPJ to new `RandomFuns` umbrella

### ISSUE THREAD

**Issue by yebai** [TuringLang/GPMLj.jl#3]
We can consider moving this repo to the following umbrella after it is registered. 

https://github.com/RandomFuns

The goal is to gradually join forces with other Julia GP packages, and create a solid GP ecosystem (basic GP, Bayes Optimisation, GPSSM etc) using Julia. 

cc @willtebbutt @trappmartin

**Comment by trappmartin** [comment]
Would it be possible to call it `RandomFunctions` instead?
